# Generated by Django 5.1.4 on 2026-09-27 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('gerar_jardinagem', 'Gerar serviços automáticos — Jardinagem'), ('gerar_limpeza_predial', 'Gerar serviços automáticos — Limpeza Predial'), ('email_resumo_diario', 'E-mail: resumo diário dos gerentes'), ('email_atrasados', 'E-mail: serviços atrasados'), ('email_concluidos', 'E-mail: serviços concluídos')], max_length=40, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('frequencia', models.CharField(choices=[('diaria', 'Uma vez por dia, a partir do horário'), ('continua', 'A cada rodada do agendador')], default='diaria', max_length=20)),
                ('horario', models.TimeField(help_text='Horário mínimo para rodar (rotinas diárias).')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField()),
                ('origem', models.CharField(choices=[('agendador', 'Agendador'), ('manual', 'Manual (painel)'), ('terminal', 'Terminal')], default='agendador', max_length=20)),
                ('status', models.CharField(choices=[('executando', 'Executando'), ('sucesso', 'Sucesso'), ('erro', 'Erro'), ('ignorada', 'Ignorada')], default='executando', max_length=20)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('itens_processados', models.PositiveIntegerField(default=0)),
                ('itens_criados', models.PositiveIntegerField(default=0)),
                ('itens_ignorados', models.PositiveIntegerField(default=0)),
                ('detalhes', models.TextField(blank=True)),
                ('executado_por', models.CharField(blank=True, max_length=150)),
                ('rotina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='automacoes.rotina')),
            ],
            options={
                'ordering': ['-iniciada_em'],
                'indexes': [models.Index(fields=['rotina', 'data_referencia', 'status'], name='automacoes__rotina__3314ae_idx')],
            },
        ),
    ]
