# Generated by Django 5.1.4 on 2026-09-27 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receber_resumo_diario', models.BooleanField(default=True)),
                ('receber_atrasados', models.BooleanField(default=True)),
                ('receber_concluidos', models.BooleanField(default=True)),
                ('gerente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_notificacao_ops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacaoEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=180, unique=True)),
                ('tipo', models.CharField(choices=[('resumo_diario', 'Resumo diário'), ('atrasado', 'Serviço atrasado'), ('concluido', 'Serviço concluído'), ('teste', 'E-mail de teste')], max_length=30)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('falhou', 'Falhou')], default='enviado', max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('assunto', models.CharField(max_length=200)),
                ('referencia', models.CharField(blank=True, help_text='id_random do serviço, quando houver', max_length=40)),
                ('setor', models.CharField(blank=True, max_length=30)),
                ('erro', models.TextField(blank=True)),
                ('tentativas', models.PositiveSmallIntegerField(default=1)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_ops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
                'indexes': [models.Index(fields=['tipo', 'status', 'criada_em'], name='notificacoe_tipo_7e7f7c_idx')],
            },
        ),
    ]
