headers_report_services = [
    # id_acompanhamento, id_random_acompanhamento, id_agendamento, id_random_agendamento,
    # colaboradores_chamados_id, colaboradores_chamados_id_random, colaboradores_chamados, data_hora_chegada,
    # data_hora_retorno, tempo_na_area
    'Acompanhamento.Id',
    'Acompanhamento.IdRandom',
    'Agendamento.Id',
    'Agendamento.IdRandom',
    'Colaboradores.Id',
    'Colaboradores.IdRandom',
    'Colaboradores.Nome',
    'DataHoraChegada',
    'DataHoraRetorno',
    'TempoEmAtividade',
    'UrlDepois'
]

headers_report_schedules = [
    # tipodeempresa, empresaprestadora, id_agendamento, id_random_agendamento,
    # id_config, tipo_agendamento, descricao_do_servico, colaboradores_chamados, colaboradores_chamados_id,
    # colaboradores_chamados_id_random, servicos_solicitados, servicos_solicitados_id, servicos_solicitados_id_random,
    # data_de_inicio,
    # data_de_conclusao, antes, depois, status_servico, area_atendida, area_atendida_id, id_random_area,
    # periodicidade_de_retorno
    # area_total, tipo_vegetacao, tipo_terreno, localidade, lat, long, unidade
    'Empresa.Tipo',
    'Empresa.Nome',
    'Agendamento.Id',
    'Agendamento.IdRandom',
    'Agendamento.IdConfiguração',
    'Agendamento.Tipo',
    'Serviço.Descrição',
    'Colaboradores.Nome',
    'Colaboradores.Id',
    'Colaboradores.IdRandom',
    'Serviço.Nome',
    'Serviço.Id',
    'Serviço.IdRandom',
    'DataHoraInicio',
    'DataHoraConclusão',
    'UrlAntes',
    'UrlDepois',
    'Status',
    'Área.Nome',
    'Área.Id',
    'Área.IdRandom',
    'Área.Periodicidade',
    'Área.Dimensão',
    'Área.TipoVegetação',
    'Área.TipoTerreno',
    'Localidade.Nome',
    'Localidade.Latitude',
    'Localidade.Longitude',
    'Unidade.Nome',
]
